title: UpTrain Documentation
description: An open-source framework to observe ML applications
theme: just-the-docs

url: https://https://dominastorm.github.io/

logo: "/assets/images/uptrain-logo.png"

favicon_ico: "/assets/images/favicon.ico"
